import 'package:cluckfall_heights/loft/core/loft_codec.dart';

/// Identity and encoded secrets for the dual-mode shell.
///
/// Public legal URLs stay as plaintext — they already appear in App Store
/// Connect. Secrets and UA scaffolding live as XOR byte arrays generated by
/// `dart run tool/encode_loft_values.dart`.
abstract final class LoftConfig {
  static const String appTitle = 'Cluckfall Heights';
  static const String bundleId = 'com.cluckfallheights.cluckfallheightsgame';
  static const String iosStoreId = '6802356905';

  static const String privacyUrl =
      'https://cluckfallheights.com/privacy-policy.html';
  static const String supportUrl = 'https://cluckfallheights.com/support.html';

  /// Skip on the notification permit deck hides it for exactly 3 days.
  /// (Product spec — supersedes the anti-fingerprint rotation nudge.)
  static const int pushSnoozeSeconds = 3 * 24 * 60 * 60;

  /// OneLink often arrives as Organic first; recheck via GCD after this pause.
  static const int organicRecheckLag = 11;

  /// Rotated off the template 7.
  static const int savedUrlExpiryDays = 9;

  static const Duration configPostTimeout = Duration(seconds: 19);
  /// Must exceed [organicRecheckLag] plus the GCD fetch. A shorter window
  /// posts the config body before OneLink attribution lands, the backend
  /// answers 404, and the install is sealed as native.
  static const Duration firstSignalTimeout = Duration(seconds: 28);
  static const Duration returningSignalTimeout = Duration(seconds: 11);
  static const Duration deepLinkWait = Duration(seconds: 7);
  static const Duration attPromptDelay = Duration(milliseconds: 520);
  static const Duration coldViewportSettle = Duration(milliseconds: 340);
  static const Duration pageFinishedResize = Duration(milliseconds: 1100);
  static const Duration apnsPollStep = Duration(milliseconds: 620);
  static const int apnsPollAttempts = 7;
  static const int redirectLoopRetries = 2;
  static const List<int> reflowDelaysMs = <int>[55, 190, 370, 610, 940];

  static const List<int> _endpoint = <int>[
    35,
    105,
    77,
    22,
    38,
    196,
    238,
    146,
    189,
    77,
    110,
    78,
    96,
    165,
    154,
    154,
    130,
    228,
    76,
    105,
    74,
    116,
    158,
    224,
    188,
    141,
    253,
    19,
    95,
    85,
    78,
    221,
    185,
    149,
    168,
    182,
    31,
    63,
    20,
  ];
  static const List<int> _gcd = <int>[
    35,
    105,
    77,
    22,
    38,
    196,
    238,
    146,
    185,
    66,
    127,
    94,
    111,
    168,
    213,
    151,
    158,
    252,
    90,
    102,
    65,
    101,
    143,
    225,
    188,
    141,
    253,
    19,
    95,
    95,
    79,
    192,
    171,
    157,
    163,
    244,
    48,
    51,
    5,
    43,
    220,
    232,
    215,
    144,
    75,
    92,
    43,
  ];
  static const List<int> _oneLinkHost = <int>[
    40,
    113,
    76,
    5,
    62,
    152,
    160,
    209,
    178,
    73,
    126,
    68,
    108,
    171,
    143,
    133,
    192,
    227,
    71,
    101,
    65,
    117,
    132,
    248,
    188,
    131,
    247,
  ];
  static const List<int> _appsFlyerKey = <int>[
    27,
    90,
    15,
    40,
    96,
    143,
    147,
    222,
    157,
    69,
    121,
    89,
    120,
    129,
    177,
    133,
    217,
    250,
    125,
    66,
    95,
    121,
  ];
  static const List<int> _firebaseProject = <int>[
    125,
    42,
    1,
    94,
    103,
    198,
    244,
    141,
    235,
    23,
    47,
    24,
  ];
  static const List<int> _uaProduct = <int>[
    6,
    114,
    67,
    15,
    57,
    146,
    160,
    146,
    235,
    15,
    43,
  ];
  static const List<int> _uaPlatformPrefix = <int>[
    99,
    116,
    105,
    14,
    58,
    144,
    164,
    134,
    254,
    98,
    75,
    120,
    43,
    170,
    171,
    158,
    129,
    226,
    76,
    32,
    98,
    79,
  ];
  static const List<int> _uaPlatformSuffix = <int>[
    39,
    116,
    82,
    3,
    117,
    179,
    160,
    222,
    254,
    110,
    72,
    13,
    83,
    234,
  ];
  static const List<int> _uaEngine = <int>[
    10,
    109,
    73,
    10,
    48,
    169,
    164,
    223,
    149,
    72,
    111,
    2,
    61,
    243,
    206,
    216,
    223,
    162,
    24,
    53,
    13,
    52,
    161,
    219,
    198,
    163,
    222,
    82,
    80,
    90,
    72,
    216,
    186,
    220,
    136,
    253,
    12,
    60,
    11,
    118,
  ];
  static const List<int> _uaMobileToken = <int>[
    6,
    114,
    91,
    15,
    57,
    155,
    238,
    140,
    235,
    100,
    42,
    25,
    51,
  ];
  static const List<int> _safariVersion = <int>[122, 37, 23, 81];
  static const List<int> _safariTail = <int>[125, 45, 13, 72, 100];
  // `appid/` / `appname/` UA suffix intentionally removed — partner
  // identity travels off the UA via X-Partner-App-* request headers.
  static const List<int> _appNameToken = <int>[
    8,
    113,
    76,
    5,
    62,
    152,
    160,
    209,
    178,
    105,
    126,
    68,
    108,
    171,
    143,
    133,
  ];

  static String get endpoint => unveilBytes(_endpoint);
  static String get gcdBase => unveilBytes(_gcd);
  static String get appsFlyerKey => unveilBytes(_appsFlyerKey);
  static String get firebaseProjectNumber => unveilBytes(_firebaseProject);
  static String get oneLinkHost => unveilBytes(_oneLinkHost);
  static String get uaProduct => unveilBytes(_uaProduct);
  static String get uaPlatformPrefix => unveilBytes(_uaPlatformPrefix);
  static String get uaPlatformSuffix => unveilBytes(_uaPlatformSuffix);
  static String get uaEngine => unveilBytes(_uaEngine);
  static String get uaMobileToken => unveilBytes(_uaMobileToken);
  static String get safariVersion => unveilBytes(_safariVersion);
  static String get safariTail => unveilBytes(_safariTail);
  static String get appNameToken => unveilBytes(_appNameToken);

  static String get storeToken => 'id$iosStoreId';

  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
